---
# update_debian_ubuntu_source/tasks/main.yml

- name: 'Update all sources on Debian/Ubuntu/...'
  ansible.builtin.apt:
    update_cache: 'yes'
    cache_valid_time: 3600
  when: 'ansible_os_family == "Debian"'
